source "https://rubygems.org"

gem "google-protobuf", "~> 3.25"
gem "grpc", "~> 1.60"
gem "toml-rb", "~> 2.2"
gem "pycall", "~> 1.5"
gem "fiddle", "~> 1.1"
gem "ostruct", "~> 0.6.3"

group :development, :test do
  gem "grpc-tools", "~> 1.60"
  gem "minitest", "~> 5.20"
  gem "rake", "~> 13.0"
  gem "webmock", "~> 3.20"
  gem "simplecov", "~> 0.22.0"
  gem "standard", "~> 1.52.0"
end
