require 'bundler/gem_tasks'
require "rake/testtask"
require_relative "lib/modal/version"

desc "Run tests"
Rake::TestTask.new(:test) do |t|
  ENV['MODAL_PROFILE'] = 'modal-rb-testing'
  ENV['MODAL_TOKEN_ID'] = 'test-token-id'
  ENV['MODAL_TOKEN_SECRET'] = 'test-token-secret'
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/test_*.rb"]
  t.verbose = ENV["ENABLE_VERBOSE"] ? true : false
  t.warning = true
end

desc "Generate Protobuf files"
task :generate do
  sh "bundle exec grpc_tools_ruby_protoc --ruby_out=lib --grpc_out=lib --proto_path=../modal-client ../modal-client/modal_proto/*.proto"
end

task default: [:generate, :test]
