# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: modal_proto/task_command_router.proto for package 'modal.task_command_router'

require 'grpc'
require 'modal_proto/task_command_router_pb'

module Modal
  module TaskCommandRouter
    module TaskCommandRouter
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'modal.task_command_router.TaskCommandRouter'

        # Poll for the exit status of an exec'd command.
        rpc :TaskExecPoll, ::Modal::TaskCommandRouter::TaskExecPollRequest, ::Modal::TaskCommandRouter::TaskExecPollResponse
        # Execute a command in the task.
        rpc :TaskExecStart, ::Modal::TaskCommandRouter::TaskExecStartRequest, ::Modal::TaskCommandRouter::TaskExecStartResponse
        # Write to the stdin stream of an exec'd command.
        rpc :TaskExecStdinWrite, ::Modal::TaskCommandRouter::TaskExecStdinWriteRequest, ::Modal::TaskCommandRouter::TaskExecStdinWriteResponse
        # Get a stream of output from the stdout or stderr stream of an exec'd command.
        rpc :TaskExecStdioRead, ::Modal::TaskCommandRouter::TaskExecStdioReadRequest, stream(::Modal::TaskCommandRouter::TaskExecStdioReadResponse)
        # Wait for an exec'd command to exit and return the exit code.
        rpc :TaskExecWait, ::Modal::TaskCommandRouter::TaskExecWaitRequest, ::Modal::TaskCommandRouter::TaskExecWaitResponse
        # Mount an image at a directory in the container.
        rpc :TaskMountDirectory, ::Modal::TaskCommandRouter::TaskMountDirectoryRequest, ::Google::Protobuf::Empty
        # Snapshot a directory with a mounted image, including any local changes, into a new image.
        rpc :TaskSnapshotDirectory, ::Modal::TaskCommandRouter::TaskSnapshotDirectoryRequest, ::Modal::TaskCommandRouter::TaskSnapshotDirectoryResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
